### PR TITLE
generic handling for "sensor" types

### PR DESCRIPTION
**Pull request by tomwpublic**
@ogiewon, can I get your eyes on this change before submitting, since I haven't tested it for functionality?

### CODE REVIEW

**Comment by ogiewon** [comment]
I am testing your updated version now...  @stephack and I were discussing making the exact same change earlier.  I'll let you now how it goes.

**Comment by tomwpublic** [comment]
> I am testing your updated version now... @stephack and I were discussing making the exact same change earlier. I'll let you now how it goes.

I found a bug (which I assume that you already found and fixed).  I committed the change to my dev branch.

**Comment by ogiewon** [comment]
@tomwpublic - I am seeing some issue with temperature and humidity devices throwing errors in my HE logs.  Do you mind if I take a stab at refactoring some of the code to hopefully simplify it, and make it much more straightforward to add new sensor-type devices?  It may take me a few hours to get things sorted and tested, but I believe it will simplify the overall design greatly.  Thoughts?

**Comment by tomwpublic** [comment]
> Do you mind if I take a stab at refactoring some of the code to hopefully simplify it, and make it much more straightforward to add new sensor-type devices?

Sure thing.  For reference, I stubbed out two drivers outside of the "hubitat" namespace until (if?) this request is fulfilled: https://community.hubitat.com/t/a-word-about-ha-he-integration/63754/58

I thought those might be useful during your refactor in case drivers from other namespaces might be needed in the future.

This is what I had in mind (with `"hubitat"` being the default value if the caller of this found null in `mapping?.namepace`):

```
def translateSensorTypes(device_class, etat = null)
{
    def mapping =
        [
            humidity: [type: "Generic Component Humidity Sensor", attributes: [name: "humidity", value: etat?.toFloat()?.toString()]],
            illuminance: [type: "Generic Component Illuminance Sensor", namespace: "community", attributes: [name: "illuminance", value: etat?.toFloat()?.toString()]],
            pressure: [type: "Generic Component Pressure Sensor", namespace: "community", attributes: [name: "pressure", value: etat?.toFloat()?.toString()]],
            temperature: [type: "Generic Component Temperature Sensor", attributes: [name: "temperature", value: etat?.toFloat()?.toString()]],
            voltage: [type: "Generic Component Voltage Sensor", attributes: [name: "voltage", value: etat?.toFloat()?.toString()]]
        ]
    return mapping[device_class]
}
```

**Comment by ogiewon** [comment]
I have updated the Parent with my latest refactored version, which supersedes this PR.

**Pull request closed without merging**
