### PR TITLE
Adding binary sensors - Separating devices

### PR DESCRIPTION
**Pull request by doonce**
I did my best to compare the binary sensors within HA and match them up with their Hubitat counterparts. I had to take a new direction in translating devices since there is a "lock" device and "lock" binary_sensor, so it will now look based on domain as well as device_class. Binary sensor classes are [here](https://www.home-assistant.io/integrations/binary_sensor/), sensor classes are [here](https://www.home-assistant.io/integrations/sensor#device-class), and it will assume other things are devices.

There are a few HA binary sensors that **should** work in Hubitat, but there isn't a Generic Component available including gas sensor, sound sensor, tamper sensor, light sensor (also conflicts with light device, another reason I separated), etc. However, a lot of these can be hacked into use by just setting them as motion sensors or another Generic Binary Component, but I didn't want to do that here.

Everything I added has been tested using template devices in HA.

### CODE REVIEW

**Comment by ymerj** [comment]
Please do not include formatting changes in your PR.

Also, it is likely to be conflicting with the upcoming version 1.38. Better wait until said version becomes official and make a new PR then.

**Comment by doonce** [comment]
> Please do not include formatting changes in your PR.
> 
> Also, it is likely to be conflicting with the upcoming version 1.38. Better wait until said version becomes official and make a new PR then.

What formatting changes are you referring to? If you mean the deletion of trailing spaces, I didn't make those changes. Maybe they're from Atom?

EDIT: yep. https://flight-manual.atom.io/using-atom/sections/editing-and-deleting-text/ so you want the trailing whitespace?

**Comment by ymerj** [comment]
Cleanup has already been done in the upcoming version.

The reason is simply because it makes it very daunting to distinguish between the code changes vs formating changes when trying to evaluate your request. I'm just asking to not make the task more difficult then it has to be.

**Comment by doonce** [comment]
Ok, got it. Again I didn't do it intentionally, it was done automatically by Atom when I cloned the current repo and I didn't know you already fixed it. I will wait for the new version to do the PR if you want. Any comments on non-whitespace related changes for my next PR?

**Comment by ymerj** [comment]
Thank you for your understanding.

Like I said, I did not look too much at it because of number of changes. I am focusing on the climate support right now. We will gladely look at yours when this is done.

**Comment by ymerj** [comment]
As expected your PR is conflicting with the new version. Please make a new PR so we can review your proposed changes.

Don't bother about the whitespace, we can ignore it in the review

**Comment by doonce** [comment]
Had to refork repository, new PR here: https://github.com/ymerj/HE-HA-control/pull/44

**Pull request closed without merging**
